### ISSUE TITLE
Optikey 2.8.0 failed to start.

### ISSUE THREAD

**Issue by Sheeva007** [OptiKey/OptiKey#350]
Optikey 2.8.0 failed to start under windows 10. 
At boot time or manualy. Nothing appears no error requster just, nothing.
The only cure is downgrading to 2.7.0 and every run again.

**Comment by zelmon64** [comment]
Could you please try to run Optikey 2.8.0 then post your resulting `\AppData\Roaming\JuliusSweetland\OptiKey\Logs\OptiKey.log` file? To ensure the log file is for the 2.8.0 attempt you could delete it before trying to run Optikey 2.8.0.

**Comment by Sheeva007** [comment]
Here it is
Thx.

[OptiKey.log.txt](https://github.com/OptiKey/OptiKey/files/1238565/OptiKey.log.txt)

**Comment by zelmon64** [comment]
I can see the problem and should be able to provide a patched version shortly.

**Comment by zelmon64** [comment]
Try replacing "C:\Program Files (x86)\OptiKey\OptiKey.exe" with this patched version. It's not quite a complete fix but it should do for now.
[OptiKey_v2.8.0_patch1.zip](https://github.com/OptiKey/OptiKey/files/1238695/OptiKey_v2.8.0_patch1.zip)

**Comment by JuliusSweetland** [comment]
@zelmon64 Hi William. I've been driving all day and offline since I released 2.8.0 - what is causing the problems? I see BadFormatExceptions.

**Comment by zelmon64** [comment]
@JuliusSweetland I think it's the startup checks for Presage. I triggered the DllNotFoundException error and it's not handling that correctly either. The patch I did handles DllNotFoundException so I'm hoping it'll handle BadFormatExceptions as well.

I'll do some tests on 2.7.0.

**Comment by JuliusSweetland** [comment]
Thank you. I'm looking into the MaryTTS unobserved issue. This one: https://github.com/OptiKey/OptiKey/issues/351

**Comment by JuliusSweetland** [comment]
@zelmon64 Does the fix you are looking at also address this issue? https://github.com/OptiKey/OptiKey/issues/349

I'm guessing it would...

**Comment by zelmon64** [comment]
@JuliusSweetland Yes I'm guessing it would as well, at least in part. With this issue OptiKey isn't handling the absence of Presage correctly whereas in 349 it seems like Presage is there but isn't being detected correctly.

I tested 2.7.0 and it's not handling DllNotFoundException correctly either. I think I may have only visually inspected commit 6201d17e239a83a6c24dafa97bf59027c00e6702 rather than manually triggering the errors to check the responses sorry.

As I said, reverting the check in that commit works for the debug version but not the release. I think it's due to the optimisation because if I disable it for the release, the fix works. Do you know much about the optimisation option? So far I read about trying to use `#pragma optimize("", off) ` to disable it for a specific function but haven't been able to find somewhere to put it yet that prevents this problem.

**Comment by JuliusSweetland** [comment]
@zelmon64 I think I've found and fixed the issue... give me a couple of minutes

**Comment by JuliusSweetland** [comment]
@zelmon64 Ok I've just committed fixes. I'll prepare 2.9.0 to supersede 2.8.0 and ask you to test before I release publicly.

The problem is that the user has Presage 64 bit installed. When OptiKey instantiates a new Presage class it fails with a BadImageFormatException, which is caught. OptiKey correctly changes the suggestion method to NGram and alerts the user, BUT... the Presage object is still alive. At some non-deterministic point in time the garbage collector comes along and attempts to finalise the Presage object, which it can't do as the format is incompatible - hence OptiKey crashes. This may not happen, but it probably will and at an uncertain point in time. I have detected this and suppressed finalisation. The user needs the 32 bit version.

**Comment by JuliusSweetland** [comment]
@Sheeva007 Please can you check whether you have the 32 or 64 bit version of Presage 0.9.2 installed? I suspect you have the 64 bit version installed (OptiKey requires the 32 bit version). You can tell from the install location; if you are running a 64 bit operating system (which your logs say you are "OS bitness: 64-Bit") then check if it is installed in "Program Files" (you installed the 64 bit version) of "Program Files (x86)" (you have the 32 bit version).

If you have the 64 bit version please uninstall it, install the 32 bit version, and try again.

**Comment by JuliusSweetland** [comment]
Fixes released in 2.9.0

**Comment by JuliusSweetland** [comment]
@zelmon64 2.9.0 pre-release is available here: https://github.com/OptiKey/OptiKey/releases

Could you please test and let me know if you are happy?

Also, out of interest how were you replicating the issue in this thread?

**Comment by zelmon64** [comment]
@JuliusSweetland I wasn't sure how to trigger the `BadImageFormatException` so I was testing the `DllNotFoundException` error by renaming the Presage installation folder.

Now that I know installing the 64-bit Presage triggers `BadImageFormatException` I tested 2.9.0 pre-release for both errors. The debug version handles both fine but the release still crashes. If I turn on optimisation for the debug version it crashes as well. The error it crashes with is:
```
2017-08-21 17:38:29,004 [ 2] ERROR JuliusSweetland.OptiKey.App: An UnhandledException has been encountered...
System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at presage.Presage.presage_free(IntPtr presage)
   at presage.Presage.Finalize()
```
(and similar for `DllNotFoundException` if I trigger the crash with that).

Whether OptiKey crashes or it handles the error correctly it causes the mouse cursor to be a bit laggy for a short time after OptiKey is closed/crashed. If Presage is not set as the suggestion method there is no lag afterwards.

**Comment by zelmon64** [comment]
@JuliusSweetland I added a log at every stage in `App_OnStartup` and the `UnhandledException` appears to happen at the line [mainWindow.Show();](https://github.com/OptiKey/OptiKey/blob/6201d17e239a83a6c24dafa97bf59027c00e6702/src/JuliusSweetland.OptiKey/App.xaml.cs#L211).

**Comment by Sheeva007** [comment]
@JuliusSweetlanYou have right. My version of presage was x64. I had to remove it and install x32. After instaling Optikey 2.9.0 pre-release everything appear to working fine. Thanks all for your reactivity. Amazing !! If you are searching for beta-tester you have my contact now. :-)

**Comment by Sheeva007** [comment]
@JuliusSweetland Just one problem appear. Optikey crash when outgoing of  settings even if i use ok or cancel.

**Comment by JuliusSweetland** [comment]
@Sheeva007 Thanks for confirming and for the offer. I am increasing OptiKey's robustness now. I'll let you know when there is a new pre-release ready to test.

**Comment by JuliusSweetland** [comment]
@Sheeva007 @zelmon64  Check out v2.9.0 now - I've just released a new version: https://github.com/OptiKey/OptiKey/releases/tag/v2.9.0.3

**Comment by zelmon64** [comment]
@JuliusSweetland v2.9.0.3 handles both errors excellently! Plus no mouse lag. 

I wasn't able to reproduce Sheeva007's crash when closing the settings though.

**Comment by JuliusSweetland** [comment]
@zelmon64 Same - I couldn't replicate the settings windows crash, BUT it may have been related to the Presage finaliser being called - it can happen at any point and take down OptiKey. I've now moved as many preventative checks as I could before the Presage constructor test (which can still cause problems).

If you're happy then I'm happy - I'm going to make this the official release now. Thanks for testing and your help!

**Comment by zelmon64** [comment]
@JuliusSweetland I happy! =D

**Comment by Sheeva007** [comment]
@JuliusSweetland Download link dead. Error 404. :-(

**Comment by zelmon64** [comment]
@Sheeva007 try this:
https://github.com/OptiKey/OptiKey/releases/tag/v2.9.0
or the top of
https://github.com/OptiKey/OptiKey/releases/

**Comment by JuliusSweetland** [comment]
Thanks William. I did some cleaning up and removed a few releases.
