### ISSUE TITLE
Brazilian Simplified Keyboard as dynamic keyboard

### ISSUE THREAD

**Issue by alandbm** [OptiKey/OptiKey#855]
My father is a ALS person.

@alexandre-mbm and I want to extend the simplified keyboard to contain "ç", accents, and a predictive line, preferably by using Presage.
We did an initial calculation and came to the conclusion that we need to design 27 interlinked dynamic keyboards.

I would like to know if there is a way to convert the simplified keyboard that is available for English to  dynamic keyboards, or if anyone have an algorithmic approach to achieve the same result with less code.

The patient is no longer able to obtain agility and precision in eye tracking and uses a Tobii Eye 5. Attempts were made with ready-made sentences, but typing is a requirement.

**Comment by alexandre-mbm** [comment]
We see the XAML file https://github.com/OptiKey/OptiKey/blob/master/src/JuliusSweetland.OptiKey.Core/UI/Views/Keyboards/English/SimplifiedConversationAlpha1.xaml

And there is the #674

**Comment by kmcnaught** [comment]
@alandbm @alexandre-mbm this is an interesting question, I will have a think about the best way to achieve this, if you could please answer a couple more questions for me.

A - Where did you envisage accents/diacritics going? If you could draw a quick sketch of a couple of the keyboards that would be helpful. 

B - Are there any keys on the simplified keyboard you would be happy to lose? e.g. calibrate or Shift?

C - Do either of you have experience with python or other scripting languages?

In terms of the issues you raise, I believe @AdamRoden has removed the scratchpad clearing between keyboards, but I'm not sure if that code has been released yet. If not, this is a good chance to revisit the issue.

@alexandre-mbm I don't understand your issue 2 - do you just mean that the prediction line should continue working between keyboards? I think this will be the case as long as the scratchpad isn't erased.

**Comment by alexandre-mbm** [comment]
Hello, @kmcnaught!

**A** - Yes, I will skechting them... @alandbm is at job. We are brothers.

**B** - ``Shift`` maybe, and another. Calibration from some tracked screen is a feature very important, but we can put it in a Menu layout also.

**C** - I am Python skilled by using reference documentation. I am not a professional programmer but I know topics of software engineering.

Goal! I was thinking on generating the XML files by scripting already. It would be a good opportunity for my brother see utility in those "things"/studies.

Yes, you understood about the prediction line. Fine.

**Comment by alexandre-mbm** [comment]
> I was thinking on generating the XML files by scripting already. It would be a good opportunity for my brother see utility in those "things"/studies.

Humm... the migration intented at issue #767 could be some type of "XAML (built-in) -> XML (Dynamic Keyboards)" transformation, is true!

**Comment by alexandre-mbm** [comment]
> **A** - Yes, I will skechting them...

For purposes of comparison and organization of the ideas, I have captured screenshots of the main layouts existing today:

![SL1](https://user-images.githubusercontent.com/957501/184631551-a4124ac6-fdb4-4d86-a977-f2471b23a281.png)

![SL2](https://user-images.githubusercontent.com/957501/184631556-6225eff5-24a3-4b69-abca-2bf8d1bfda43.png)

![SL3](https://user-images.githubusercontent.com/957501/184631560-d005bf5c-f110-432e-8717-fefaebfe93e9.png)

![SN1](https://user-images.githubusercontent.com/957501/184631562-de4a3352-edd0-4f24-a935-559a02ea1215.png)

**Comment by alexandre-mbm** [comment]
I think that our father needs the keyboard layout bellow:

![IMG-20220815-WA0000](https://user-images.githubusercontent.com/957501/184644013-4895878d-9009-4dde-abce-9fad9fda600d.jpg)

**Comment by alexandre-mbm** [comment]
> Naturally the things will are implemented starting from simpler (beginning with blank cells)...

Yesterday I was not online because at job. Daytime. Brasília's timezone.

_Update_

It will be easy to make a MVP (minimal valuable product) containing nine dynamic keyboards. The diacritics and "Shift" features may start out empty. For talking, capital letters are not required.

Accented words are fixed by autocomplete. Presage! This is how it works everyday on our smartphones.

**Comment by kmcnaught** [comment]
Hi @alexandre-mbm, here's a starting point for you in python:

https://github.com/kmcnaught/optikey-keyboard-scripts

Use python 3 (I have 3.6.7) and run `make_xml.py`

It looks like we do still have the scratchpad clearing issue in the master branch, I fixed it in my local version of Optikey to show what it looks like - I'll have to solve it better later.

Video:
https://user-images.githubusercontent.com/12151404/185191897-b1d100b7-82b3-473e-92b9-930ea0a7a82e.mp4

The main thing I learned is that it is really quite simple to make sub-keyboards **if** the only custom keys are simple characters - then every character just has a label and a text element with the same value. It will get trickier if you want some of the keys to perform actions, for instance a Shift key or a Space key. It might be simplest to leave these out of the automatic generation step, and then add them manually. 

Other comments
- sometimes it was easier to have things hard-coded in the skeleton xml file, other times I add them in python - there should be examples of both methods
- I haven't tested with presage but assume you'd just need to switch the prediction engine in optikey's settings
- I tried adding diacritics to the current strategy and it fails due to a unicode error. I'm sure this is fixable if you spend a bit of time playing with string encodings. 
- I added a Speak key instead of a Back button because I misremembered the picture you drew!

Take a look at the python, it's not polished! Let me know if any of it doesn't make sense and then try to extend it further :-) I'll tackle the scratchpad-clearing issue separately

**Comment by alexandre-mbm** [comment]
@kmcnaught, thank you very much! You have delivered the "our" MVP and the essential know how already, **the Tip.** Very good! I will be looking all more slowing...

**Comment by kmcnaught** [comment]
I just fixed a small bug in the script - it is intended that top.xml is visible from the dynamic keyboard menu, but the sub menus are hidden. This wasn't the case in the video I recorded. I just fixed it, however, for testing you may prefer to remove it so you can easily test every keyboard. Just comment out this line:

https://github.com/kmcnaught/optikey-keyboard-scripts/blob/main/make_xml.py#L84

**Comment by alexandre-mbm** [comment]
@kmcnaught, in really, [it is not to be into Grid](kmcnaught/optikey-keyboard-scripts#2)

**Comment by alexandre-mbm** [comment]
In my initial testing I have identified a couple of new Optikey's issues:
- [ ] Capital letters for are not disabled from Console, the checkboxes doesn't work
- [ ] When starting the Optkey instance at `top.xml`, the **Maximised** have not effect

**Comment by alexandre-mbm** [comment]
> https://github.com/kmcnaught/optikey-keyboard-scripts

We are satisfied with the current layout for while. Thank you very much!
**The problem is to config fixations now.**
